services:
  backend:
    container_name: nedi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    container_name: nedi-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3001:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
